SET search_path TO entask;


CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  email VARCHAR(64) NOT NULL,
  given_name VARCHAR(64) NOT NULL,
  family_name VARCHAR(64) NOT NULL,
  picture_url TEXT,
  last_login TIMESTAMP
);
