include:
  - ./compose/core.compose.yaml
  - ./compose/nats.compose.yaml
  - ./compose/services.compose.yaml
  - ./compose/converters.compose.yaml
  - ./core/conductor/docker/docker-compose.yaml
        
networks:
  entask:
    name: entask