CREATE TABLE conversions (
  id SERIAL PRIMARY KEY,
  conversion_type VARCHAR(255) NOT NULL,
  submitted_by MEDIUMINT(8) UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  failed TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  finished TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  conversion_status VARCHAR(32) NOT NULL DEFAULT 'pending'
)