providers:
  docker:
    network: "entask"
    watch: true

api:
  dashboard: true
  insecure: true
  
entrypoints:
  http:
    address: ":80"
  https:
    address: ":443"
  dashboard:
    address: ":9091"
  
http:    
  routers:
    auth:
      rule: "PathRegexp(`/api/auth(.*?)`)"
      service: auth-service
    
    version:
      rule: "PathRegexp(`/api/version(.*?)`)"
      service: version-service

log:
  level: DEBUG
  maxBackups: 3