services:
  term-extractor-converter-dapr:
    container_name: converter-term-extractor-dapr
    image: daprio/daprd:edge
    environment:
      DAPR_PLACEMENT_PORT: ${DAPR_PLACEMENT_PORT}
      TERM_EXTRACTOR_CONVERTER_PORT: ${TERM_EXTRACTOR_CONVERTER_PORT}
    command: [
      "./daprd",
      "--app-port", "${TERM_EXTRACTOR_CONVERTER_PORT}",
      "--app-id", "term-extractor-converter",
      "-placement-host-address", "dapr-placement:${DAPR_PLACEMENT_PORT}",
      "--resources-path", '/components',
      "--app-channel-address", "host.docker.internal"
    ]
    volumes:
      - "../converters/term-extractor/components:/components"
    depends_on:
      - term-extractor-converter
      - redis
    networks:
      - entask
    expose:
      - "${TERM_EXTRACTOR_CONVERTER_PORT}"
    labels:
      - "traefik.enable=false"
      
  text-recognizer-converter-dapr:
    container_name: converter-text-recognizer-dapr
    image: daprio/daprd:edge
    environment:
      DAPR_PLACEMENT_PORT: ${DAPR_PLACEMENT_PORT}
      TEXT_RECOGNIZER_CONVERTER_PORT: ${TEXT_RECOGNIZER_CONVERTER_PORT}
    command: [
      "./daprd",
      "--app-port", "${TEXT_RECOGNIZER_CONVERTER_PORT}",
      "--app-id", "text-recognizer-converter",
      "-placement-host-address", "dapr-placement:${DAPR_PLACEMENT_PORT}",
      "--resources-path", '/components',
      "--app-channel-address", "host.docker.internal"
    ]
    volumes:
      - "../converters/text-recognizer/components:/components"
    depends_on:
      - text-recognizer-converter
      - redis
    networks:
      - entask
    expose:
      - "${TEXT_RECOGNIZER_CONVERTER_PORT}"
    labels:
      - "traefik.enable=false"
  
  waveformer-converter-dapr:
    container_name: converter-waveformer-dapr
    image: daprio/daprd:edge
    environment:
      DAPR_PLACEMENT_PORT: ${DAPR_PLACEMENT_PORT}
      WAVEFORMER_CONVERTER_PORT: ${WAVEFORMER_CONVERTER_PORT}
    command: [
      "./daprd",
      "--app-port", "${WAVEFORMER_CONVERTER_PORT}",
      "--app-id", "waveformer-converter",
      "-placement-host-address", "dapr-placement:${DAPR_PLACEMENT_PORT}",
      "--resources-path", '/components',
      "--app-channel-address", "host.docker.internal"
    ]
    volumes:
      - "../converters/waveformer/components:/components"
    depends_on:
      - waveformer-converter
      - redis
    networks:
      - entask
    expose:
      - "${WAVEFORMER_CONVERTER_PORT}"
    labels:
      - "traefik.enable=false"
      
  thumbnailer-converter-dapr:
    container_name: converter-thumbnailer-dapr
    image: daprio/daprd
    environment:
      DAPR_PLACEMENT_PORT: ${DAPR_PLACEMENT_PORT}
      THUMBNAILER_CONVERTER_PORT: ${THUMBNAILER_CONVERTER_PORT}
    command: [
      "./daprd",
      "-app-port", "${THUMBNAILER_CONVERTER_PORT}",
      "-app-id", "thumbnailer-converter",
      "-placement-host-address", "dapr-placement:${DAPR_PLACEMENT_PORT}",
      "-components-path", '/components',
      "--app-channel-address", "host.docker.internal"
    ]
    volumes:
      - "../converters/thumbnailer/components:/components"
    depends_on:
      - thumbnailer-converter
      - redis
      - dapr-placement
    networks:
      - entask
    expose:
      - "${THUMBNAILER_CONVERTER_PORT}"
    labels:
      - "traefik.enable=false"